[package]
name = "pz-server"
edition = "2021"
version = "0.0.0"
publish = false

[dependencies]
rocket = {version = "0.5.0", features=["json"]}
pz-web = {git="https://github.com/RiverRuby/pz-web", branch="rocket"}
smallvec = "1.10.0"
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2"